# my-react-app/values.yaml


deployment:
  replicaCount: 1
  image:
    repository: docker-registry.mw.local/fittracker-backend
    tag: 0.1.0
    pullPolicy: IfNotPresent

  service:
    name: fittracker-backend
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    pathType: ImplementationSpecific
    host: fittracker.mw.local
    path: /api
  appconfig:
    db_host: postgres.mw.local
    db_name: FitTracker
    enable_otel: true
    host: 0.0.0.0
