# my-react-app/values.yaml


deployment:
  replicaCount: 1
  image:
    repository: docker-registry.mw.local/pejzen-frontend
    tag: 0.0.1-aplha.1
    pullPolicy: IfNotPresent

  service:
    name: pejzen-frontend
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    pathType: ImplementationSpecific
    path: /
    url: pejzen.mw.local
