

global:
  name: mwstack-webhookforwarder
deployment:
  replicaCount: 1
  secrets:
    enable: true
  image:
    repository: docker-registry.mw.local/mwstack-webhookforwarder
    tag: 20260204-171012-5e4cf58
    pullPolicy: IfNotPresent

  service:
    name: mwstack-webhookforwarder
    type: ClusterIP
    port: 80
    targetPort: 8080

  ingress:
    enabled: true
    pathType: ImplementationSpecific
    host: mwstack-webhookforwarder.mw.local
    path: /
    tls:
      enable: true
  
  extraManifests:
    - apiVersion: bitnami.com/v1alpha1
      kind: SealedSecret
      metadata:
        name: mwstack-webhookforwarder-secrets
        namespace: mwstack
      spec:
        encryptedData:
          token: AgCjT9kLLv+LUdbj+MFv1IpDPaTu61ajMcOMJmnq5jJyUurZJmcT6AxCNg52eHvnFaZTWXmoWYeg/h+kO76h++PnJGwfXWwBXb610eMQHQaVg2bTOdrW+1NN4X9hLEYYhGQ+72y5c//WopL6JKTWlnlwsHVV7i+gnPAO9fGqcIzssPnnAZIajRQSpqxU+lAKS8Bt9URpWrj3Vp5jja4kxDQQHCt4wAREtBf7Xage2mvKKLyZ0Oq5bY2d74iENGXZfHDCZ09cGayLjPy2nZaPoJbW+krSEe1oR484Gb758RNg3L18nkObHqqY+TpY8hEzRQpLdzLkqdvBrr7LZfPLVK6d/jT6IfuYfguztQ26dIhXDqasli39Nr6sQ6CBLVXzIQYAlD+1wgBcWAJA+Fb1cXh1YraWG7+TMpRq6K/8D9CBKnT89NLnBB8YfzXNT3EoZh/RHPAb2cuU4ggT/kVnH1xC+LvXcv0Rd77npqgRPpuQHSVOuoOt/trklXNqSfkBHelEJ6FFxVb4dAMKDljU7CGEG3VT1+f0LReIy4Qyjy5QLXndCNlOxvdzru6ZI2FQRxawULmGRhX8Z0lhwxieB8i8EMM8EdrBJZ+3BQ5RRwMCPctmkI4QrpvHVNHC8XXu61Vv3nJ39CCNRqHkNBsaDkOPgCx3lLQcs8UbYLVIKKHm6AA4/vjW7Ao/HEwHwcr5wvZH6S0ntgW7RzlTxQTHRk0wNtg2bBRdQUrMUR9uRYLqQO2yEzgeRovlkEW+GiG3R2DTlFjV9bU3mhOG999JKjFrg03EOSQxCJN+rI5p03poDVjBI9Ra4eQFcmt2E11bEdVmMR+PCO1hqGM2pcmoZB/CzrLVTE7rfc+1f6GDm59mNQ==
        template:
          metadata:
            name: mwstack-webhookforwarder-secrets
            namespace: mwstack
          type: Opaque
