# my-react-app/values.yaml


deployment:
  replicaCount: 1
  image:
    repository: docker-registry.mw.local/mwstack-webhookforwarder
    tag: 20260131-194735-8ae8907
    pullPolicy: IfNotPresent

  service:
    name: mwstack-webhookforwarder
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    pathType: ImplementationSpecific
    host: mwstack-webhookforwarder.mw.local
    path: /
