# my-react-app/values.yaml

global:
  name: mwstack-webhookforwarder
deployment:
  replicaCount: 1
  image:
    repository: docker-registry.mw.local/mwstack-webhookforwarder
    tag: 20260203-172010-89094e4
    pullPolicy: IfNotPresent

  service:
    name: mwstack-webhookforwarder
    type: ClusterIP
    port: 80
    targetPort: 8080

  ingress:
    enabled: true
    pathType: ImplementationSpecific
    host: mwstack-webhookforwarder.mw.local
    path: /
    tls:
      enable: true
